# Generated by Django 2.1.7 on 2019-03-06 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.PositiveIntegerField(default=0, unique=True, verbose_name='Telegram ID')),
                ('is_bot', models.BooleanField(default=True, verbose_name='Is User Bot')),
                ('first_name', models.CharField(default='', max_length=255, verbose_name='Name')),
                ('last_name', models.CharField(default='', max_length=255, verbose_name='Last Name')),
                ('lan_code', models.CharField(default='ru', max_length=5, verbose_name='Language Code')),
            ],
        ),
    ]
