# Generated by Django 2.1.7 on 2019-03-08 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='telegram_id',
            field=models.PositiveIntegerField(default=0, null=True, unique=True, verbose_name='Telegram ID'),
        ),
    ]
