# Generated by Django 2.1.7 on 2019-03-08 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190308_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='first_name',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='users',
            name='is_bot',
            field=models.BooleanField(default=True, null=True, verbose_name='Is User Bot'),
        ),
    ]
