# Generated by Django 2.1.7 on 2019-03-08 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190308_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='lan_code',
            field=models.CharField(default='ru', max_length=5, null=True, verbose_name='Language Code'),
        ),
        migrations.AlterField(
            model_name='users',
            name='last_name',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='Last Name'),
        ),
    ]
