# Generated by Django 2.1.7 on 2019-03-08 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190308_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='first_name',
            field=models.CharField(default='', max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='users',
            name='is_bot',
            field=models.BooleanField(default=True, verbose_name='Is User Bot'),
        ),
        migrations.AlterField(
            model_name='users',
            name='lan_code',
            field=models.CharField(default='ru', max_length=5, verbose_name='Language Code'),
        ),
        migrations.AlterField(
            model_name='users',
            name='last_name',
            field=models.CharField(default='', max_length=255, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='users',
            name='telegram_id',
            field=models.PositiveIntegerField(default=0, unique=True, verbose_name='Telegram ID'),
        ),
    ]
