# Generated by Django 2.1.7 on 2019-03-08 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190308_1941'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='users',
            name='is_bot',
        ),
        migrations.RemoveField(
            model_name='users',
            name='lan_code',
        ),
        migrations.RemoveField(
            model_name='users',
            name='last_name',
        ),
        migrations.AddField(
            model_name='users',
            name='username',
            field=models.CharField(default='', max_length=255, verbose_name='Username'),
        ),
    ]
