# Generated by Django 2.1.7 on 2019-03-11 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190309_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='Username'),
        ),
    ]
