# Generated by Django 2.1.7 on 2019-03-16 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=511, verbose_name='Название')),
                ('author', models.CharField(default='', max_length=511, verbose_name='Автор')),
                ('description', models.TextField(verbose_name='Описание')),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('rating', models.PositiveIntegerField(default=0, verbose_name='Рейтинг')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.PositiveIntegerField(default=0, unique=True, verbose_name='Telegram ID')),
                ('full_name', models.CharField(default='', max_length=255, verbose_name='Name')),
                ('username', models.CharField(default='', max_length=255, null=True, verbose_name='Username')),
            ],
        ),
    ]
