# Generated by Django 2.1.7 on 2019-03-16 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_telegramuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='phone',
            field=models.PositiveIntegerField(default=0, verbose_name='Номер телефона'),
        ),
    ]
