# Generated by Django 2.1.7 on 2019-03-16 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190316_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='published_date',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
